import type { Unit } from "./types";

export const MOCK_UNITS: Unit[] = [
  {
    slug: "present-simple",
    title: "Şimdiki Zaman",
    description: "Alışkanlıklar, genel doğrular, tarifeli olaylar — dilbilgisinin ilk taşı.",
    difficulty: "Başlangıç",
    status: "available",
    lessons: [
      {
        id: "ps-1",
        title: "Olumlu Cümle",
        description: '"I play football every day."',
        status: "completed",
        bestScore: 100,
        progress: 100,
        icon: "sun",
      },
      {
        id: "ps-2",
        title: "Olumsuz Cümle",
        description: '"I do not play football."',
        status: "completed",
        bestScore: 95,
        progress: 100,
        icon: "sparkles",
      },
      {
        id: "ps-3",
        title: "Soru Cümlesi",
        description: '"Do you play football?"',
        status: "completed",
        bestScore: 80,
        progress: 100,
        icon: "messageCircle",
      },
      {
        id: "ps-4",
        title: "3. Tekil Şahıs",
        description: '"She plays the piano."',
        status: "available",
        progress: 0,
        icon: "star",
      },
      {
        id: "ps-5",
        title: "Sık Kullanılan Fiiller",
        description: "have, do, go, come, make…",
        status: "locked",
        icon: "zap",
      },
      {
        id: "ps-6",
        title: "Ünite Sınavı",
        description: "Tüm konuların karışık soruları",
        status: "locked",
        icon: "trophy",
        isUnitExam: true,
      },
    ],
  },
  {
    slug: "past-simple",
    title: "Geçmiş Zaman",
    description: "Düzenli ve düzensiz fiiller, geçmişteki belirli olaylar.",
    difficulty: "Başlangıç",
    status: "locked",
    lessons: [
      { id: "past-1", title: "Düzenli Fiiller", status: "locked", icon: "clock" },
      { id: "past-2", title: "Düzensiz Fiiller", status: "locked", icon: "layers" },
      { id: "past-3", title: "Olumsuz Cümle", status: "locked", icon: "sparkles" },
      { id: "past-4", title: "Soru Cümlesi", status: "locked", icon: "messageCircle" },
      { id: "past-5", title: "Zaman Belirteçleri", status: "locked", icon: "zap" },
      { id: "past-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "present-continuous",
    title: "Şimdiki Sürekli Zaman",
    description: "Şu anda olmakta olan eylemler · am/is/are + V-ing yapısı.",
    difficulty: "Orta",
    status: "locked",
    lessons: [
      { id: "pc-1", title: "Olumlu Cümle", status: "locked", icon: "rocket" },
      { id: "pc-2", title: "Olumsuz Cümle", status: "locked", icon: "sparkles" },
      { id: "pc-3", title: "Soru Cümlesi", status: "locked", icon: "messageCircle" },
      { id: "pc-4", title: "-ing Yazım Kuralları", status: "locked", icon: "puzzle" },
      { id: "pc-5", title: "Şu An / Bu Sıralar", status: "locked", icon: "clock" },
      { id: "pc-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "future",
    title: "Gelecek Zaman",
    description: "Niyetler, planlar, öngörüler · will ve be going to.",
    difficulty: "Orta",
    status: "locked",
    lessons: [
      { id: "fut-1", title: "will · Olumlu", status: "locked", icon: "rocket" },
      { id: "fut-2", title: "will · Olumsuz & Soru", status: "locked", icon: "messageCircle" },
      { id: "fut-3", title: "be going to · Olumlu", status: "locked", icon: "star" },
      { id: "fut-4", title: "be going to · Olumsuz & Soru", status: "locked", icon: "sparkles" },
      { id: "fut-5", title: "will vs. going to", status: "locked", icon: "puzzle" },
      { id: "fut-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "present-perfect",
    title: "Şimdiki Bitmiş Zaman",
    description: "have/has + V3 · deneyim, yakın geçmiş, süre — for/since.",
    difficulty: "Orta",
    status: "locked",
    lessons: [
      { id: "perf-1", title: "have/has + V3 Olumlu", status: "locked", icon: "award" },
      { id: "perf-2", title: "Olumsuz & Soru", status: "locked", icon: "messageCircle" },
      { id: "perf-3", title: "already / yet / just / ever / never", status: "locked", icon: "sparkles" },
      { id: "perf-4", title: "Present Perfect vs. Past Simple", status: "locked", icon: "layers" },
      { id: "perf-5", title: "for / since", status: "locked", icon: "clock" },
      { id: "perf-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "modals",
    title: "Modal Fiiller",
    description: "can · could · should · must · may/might — yetenek, tavsiye, zorunluluk, olasılık.",
    difficulty: "Orta",
    status: "locked",
    lessons: [
      { id: "mod-1", title: "can / can't", status: "locked", icon: "zap" },
      { id: "mod-2", title: "could · geçmiş & rica", status: "locked", icon: "clock" },
      { id: "mod-3", title: "should / shouldn't", status: "locked", icon: "sparkles" },
      { id: "mod-4", title: "must / have to", status: "locked", icon: "award" },
      { id: "mod-5", title: "may / might", status: "locked", icon: "puzzle" },
      { id: "mod-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "conditionals",
    title: "Koşul Cümleleri",
    description: "If clauses · Type 0, 1, 2, 3 — gerçek, hayali, pişmanlık.",
    difficulty: "İleri",
    status: "locked",
    lessons: [
      { id: "cond-1", title: "Type 0 · Genel doğrular", status: "locked", icon: "star" },
      { id: "cond-2", title: "Type 1 · Olası gelecek", status: "locked", icon: "rocket" },
      { id: "cond-3", title: "Type 2 · Hayali şimdi", status: "locked", icon: "sparkles" },
      { id: "cond-4", title: "Type 3 · Geçmiş pişmanlık", status: "locked", icon: "clock" },
      { id: "cond-5", title: "when / if / unless", status: "locked", icon: "puzzle" },
      { id: "cond-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "passive",
    title: "Edilgen Çatı",
    description: "be + V3 · fiili yapılan işin öznesi belirsiz/önemsiz olduğunda.",
    difficulty: "İleri",
    status: "locked",
    lessons: [
      { id: "pass-1", title: "Present Simple Passive", status: "locked", icon: "book" },
      { id: "pass-2", title: "Past Simple Passive", status: "locked", icon: "clock" },
      { id: "pass-3", title: "Future Passive", status: "locked", icon: "rocket" },
      { id: "pass-4", title: "Modal Passive", status: "locked", icon: "zap" },
      { id: "pass-5", title: "Active → Passive", status: "locked", icon: "layers" },
      { id: "pass-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "past-extended",
    title: "Past Continuous & Past Perfect",
    description: "Geçmişte paralel/öncelikli olaylar — was/were + V-ing ve had + V3.",
    difficulty: "Orta",
    status: "locked",
    lessons: [
      { id: "pcp-1", title: "Past Continuous · Olumlu", status: "locked", icon: "clock" },
      { id: "pcp-2", title: "Past Continuous · Olumsuz & Soru", status: "locked", icon: "messageCircle" },
      { id: "pcp-3", title: "when / while · iki eylem", status: "locked", icon: "layers" },
      { id: "pcp-4", title: "Past Perfect · Olumlu", status: "locked", icon: "award" },
      { id: "pcp-5", title: "Past Perfect · Olumsuz & Soru", status: "locked", icon: "puzzle" },
      { id: "pcp-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "used-to",
    title: "Used to",
    description: "Geçmiş alışkanlıklar · be used to / get used to ayrımı.",
    difficulty: "Orta",
    status: "locked",
    lessons: [
      { id: "used-1", title: "used to · Olumlu", status: "locked", icon: "clock" },
      { id: "used-2", title: "used to · Olumsuz", status: "locked", icon: "sparkles" },
      { id: "used-3", title: "used to · Soru", status: "locked", icon: "messageCircle" },
      { id: "used-4", title: "used to vs. Past Simple", status: "locked", icon: "layers" },
      { id: "used-5", title: "used to vs. be used to", status: "locked", icon: "puzzle" },
      { id: "used-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "comparatives",
    title: "Karşılaştırma",
    description: "Comparatives & superlatives · -er/-est · more/most · as…as.",
    difficulty: "Orta",
    status: "locked",
    lessons: [
      { id: "comp-1", title: "Kısa sıfatlar · -er/-est", status: "locked", icon: "star" },
      { id: "comp-2", title: "Uzun sıfatlar · more/most", status: "locked", icon: "rocket" },
      { id: "comp-3", title: "Düzensiz sıfatlar", status: "locked", icon: "layers" },
      { id: "comp-4", title: "as…as · eşitlik", status: "locked", icon: "sparkles" },
      { id: "comp-5", title: "same/different/similar", status: "locked", icon: "puzzle" },
      { id: "comp-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "articles",
    title: "Tanımlıklar (Articles)",
    description: "a · an · the · tanımlıksız kullanım — özel ad kuralları.",
    difficulty: "Orta",
    status: "locked",
    lessons: [
      { id: "art-1", title: "a / an", status: "locked", icon: "book" },
      { id: "art-2", title: "the · belirli", status: "locked", icon: "star" },
      { id: "art-3", title: "a/an vs. the", status: "locked", icon: "layers" },
      { id: "art-4", title: "Tanımlıksız kullanım", status: "locked", icon: "sparkles" },
      { id: "art-5", title: "Özel adlar ve the", status: "locked", icon: "puzzle" },
      { id: "art-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "question-tags",
    title: "Question Tags",
    description: "Değil mi? — cümle sonu soruları · isn't it, don't you, didn't they…",
    difficulty: "Orta",
    status: "locked",
    lessons: [
      { id: "qtag-1", title: "be (am/is/are)", status: "locked", icon: "messageCircle" },
      { id: "qtag-2", title: "have / has", status: "locked", icon: "award" },
      { id: "qtag-3", title: "do / does", status: "locked", icon: "sparkles" },
      { id: "qtag-4", title: "Past Simple", status: "locked", icon: "clock" },
      { id: "qtag-5", title: "Modal / Future", status: "locked", icon: "rocket" },
      { id: "qtag-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "reported-speech",
    title: "Dolaylı Anlatım",
    description: "Reported speech · said/told/asked · backshift · zaman-yer değişimi.",
    difficulty: "İleri",
    status: "locked",
    lessons: [
      { id: "rs-1", title: "Statements · backshift", status: "locked", icon: "book" },
      { id: "rs-2", title: "Sorular", status: "locked", icon: "messageCircle" },
      { id: "rs-3", title: "Emir / Rica", status: "locked", icon: "award" },
      { id: "rs-4", title: "Zaman / Yer değişimleri", status: "locked", icon: "clock" },
      { id: "rs-5", title: "Modal backshift", status: "locked", icon: "puzzle" },
      { id: "rs-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "relative-clauses",
    title: "Sıfat Cümlecikleri",
    description: "who · which · that · whose · where/when/why — adlara bağlı cümlecikler.",
    difficulty: "İleri",
    status: "locked",
    lessons: [
      { id: "rel-1", title: "who / whom · insanlar", status: "locked", icon: "star" },
      { id: "rel-2", title: "which · eşya/hayvan", status: "locked", icon: "sparkles" },
      { id: "rel-3", title: "that · her ikisi", status: "locked", icon: "layers" },
      { id: "rel-4", title: "whose · iyelik", status: "locked", icon: "award" },
      { id: "rel-5", title: "where / when / why", status: "locked", icon: "puzzle" },
      { id: "rel-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "gerunds-infinitives",
    title: "Gerunds & Infinitives",
    description: "-ing vs. to + V1 · anlam değiştiren fiiller · preposition + gerund.",
    difficulty: "İleri",
    status: "locked",
    lessons: [
      { id: "gi-1", title: "Gerund (-ing) fiiller", status: "locked", icon: "sparkles" },
      { id: "gi-2", title: "Infinitive fiiller", status: "locked", icon: "rocket" },
      { id: "gi-3", title: "Anlam değiştiren", status: "locked", icon: "layers" },
      { id: "gi-4", title: "Preposition + Gerund", status: "locked", icon: "puzzle" },
      { id: "gi-5", title: "Adj + Infinitive · too/enough", status: "locked", icon: "star" },
      { id: "gi-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
  {
    slug: "phrasal-verbs",
    title: "Phrasal Verbs",
    description: "get · turn · look · take · give/put/break — en yaygın phrasal verbs.",
    difficulty: "İleri",
    status: "locked",
    lessons: [
      { id: "phv-1", title: "get + particles", status: "locked", icon: "zap" },
      { id: "phv-2", title: "turn + particles", status: "locked", icon: "rocket" },
      { id: "phv-3", title: "look + particles", status: "locked", icon: "star" },
      { id: "phv-4", title: "take + particles", status: "locked", icon: "sparkles" },
      { id: "phv-5", title: "give/put/break", status: "locked", icon: "layers" },
      { id: "phv-6", title: "Ünite Sınavı", status: "locked", icon: "trophy", isUnitExam: true },
    ],
  },
];

export function findUnit(slug: string): Unit | undefined {
  return MOCK_UNITS.find((u) => u.slug === slug);
}

export function findLesson(lessonId: string): { unit: Unit; lesson: Unit["lessons"][number] } | undefined {
  for (const unit of MOCK_UNITS) {
    const lesson = unit.lessons.find((l) => l.id === lessonId);
    if (lesson) return { unit, lesson };
  }
  return undefined;
}
